---

- name: Install pip via easy install
  easy_install: name=pip state=present

- name: ensure ntpd is at the latest version
  yum: name=ntp state=latest
  notify:
    - restart ntpd

- name: disable firewall
  service: name=firewalld enabled=no state=stopped

- name: install wget
  yum: name=wget state=latest

- name: upgrade setuptools
  shell: pip install --upgrade setuptools
  
- name: add dockerrepo to yum
  copy: src=docker.repo dest=/etc/yum.repos.d/ owner=root group=root mode=0644

- name: install docker
  yum: name=docker-engine enablerepo=dockerrepo state=present
  notify:
    - enable docker
    - start docker

- name: install ansible
  yum: name=ansible state=latest

- name: install ansible container
  pip: name=ansible-container state=latest

